# Generated by Django 3.1.2 on 2020-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
