# Generated by Django 3.1.2 on 2020-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_content2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logo')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField()),
                ('mission_and_vision', models.TextField()),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('website', models.CharField(max_length=200)),
                ('map_location', models.CharField(max_length=200)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('sponsored', models.TextField(blank=True, null=True)),
                ('sponsored1', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
