# Generated by Django 3.1.2 on 2020-10-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='sponsored',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='sponsored1',
        ),
    ]
