# Generated by Django 3.1.2 on 2020-10-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_auto_20201016_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
