# Generated by Django 3.1.2 on 2020-10-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='email',
            field=models.EmailField(default='nn', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sendmail'),
        ),
    ]
