# Generated by Django 3.1.2 on 2020-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_auto_20201018_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='map_location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
